/*
  # Add more cards to reach 55 total

  This migration adds additional credit cards and gift cards to the database
  to reach a total of 55 available cards across various types and countries.
*/

INSERT INTO cards (title, description, price, balance, card_type, card_color, rating, country, is_available) VALUES
('Premium Visa 1', 'High balance Visa card', 299, 5000, 'visa', 'blue', 4.8, 'us', true),
('Premium Visa 2', 'High balance Visa card', 349, 6500, 'visa', 'blue', 4.9, 'uk', true),
('Premium Visa 3', 'High balance Visa card', 399, 7500, 'visa', 'blue', 4.7, 'germany', true),
('Premium Mastercard 1', 'Premium Mastercard', 349, 5500, 'mastercard', 'red', 4.8, 'us', true),
('Premium Mastercard 2', 'Premium Mastercard', 399, 6500, 'mastercard', 'red', 4.9, 'canada', true),
('Premium Mastercard 3', 'Premium Mastercard', 449, 8000, 'mastercard', 'red', 4.7, 'italy', true),
('Premium AMEX', 'American Express premium', 499, 9000, 'amex', 'blue', 5.0, 'us', true),
('Premium AMEX UK', 'American Express premium', 549, 10000, 'amex', 'blue', 4.9, 'uk', true),
('Amazon Gift Card 1', 'Amazon gift card $100', 99, 100, 'gift card', 'orange', 4.9, 'us', true),
('Amazon Gift Card 2', 'Amazon gift card $250', 249, 250, 'gift card', 'orange', 4.9, 'us', true),
('Amazon Gift Card 3', 'Amazon gift card $500', 499, 500, 'gift card', 'orange', 4.9, 'us', true),
('Amazon Gift Card 4', 'Amazon gift card $100 UK', 89, 100, 'gift card', 'orange', 4.8, 'uk', true),
('Apple Gift Card 1', 'Apple store gift card $50', 49, 50, 'gift card', 'gray', 4.8, 'us', true),
('Apple Gift Card 2', 'Apple store gift card $200', 199, 200, 'gift card', 'gray', 4.8, 'us', true),
('Apple Gift Card 3', 'Apple store gift card $100', 99, 100, 'gift card', 'gray', 4.8, 'uk', true),
('Spotify Gift Card 1', 'Spotify premium 6 months', 79, 79, 'gift card', 'green', 4.7, 'us', true),
('Spotify Gift Card 2', 'Spotify premium 12 months', 159, 159, 'gift card', 'green', 4.7, 'us', true),
('Netflix Gift Card 1', 'Netflix 3 months', 44, 44, 'gift card', 'red', 4.6, 'us', true),
('Netflix Gift Card 2', 'Netflix 6 months', 89, 89, 'gift card', 'red', 4.6, 'us', true),
('Best Buy Gift Card 1', 'Best Buy $100', 99, 100, 'gift card', 'yellow', 4.8, 'us', true),
('Best Buy Gift Card 2', 'Best Buy $250', 249, 250, 'gift card', 'yellow', 4.8, 'us', true),
('PlayStation Card 1', 'PlayStation Store $50', 49, 50, 'gift card', 'blue', 4.7, 'us', true),
('PlayStation Card 2', 'PlayStation Store $100', 99, 100, 'gift card', 'blue', 4.7, 'us', true),
('Nintendo Card 1', 'Nintendo eShop $50', 49, 50, 'gift card', 'red', 4.6, 'us', true),
('Steam Gift Card 1', 'Steam $20', 19, 20, 'gift card', 'black', 4.8, 'us', true),
('PayPal Transfer 1', 'PayPal balance transfer', 129, 1500, 'paypal', 'blue', 4.9, 'us', true),
('PayPal Transfer 2', 'PayPal balance transfer', 199, 2500, 'paypal', 'blue', 4.9, 'us', true),
('PayPal Transfer 3', 'PayPal balance transfer', 149, 2000, 'paypal', 'blue', 4.8, 'uk', true),
('PayPal Transfer 4', 'PayPal balance transfer', 179, 2200, 'paypal', 'blue', 4.8, 'canada', true),
('Economy Visa 1', 'Basic Visa card', 79, 1000, 'visa', 'blue', 4.5, 'us', true),
('Economy Visa 2', 'Basic Visa card', 89, 1200, 'visa', 'blue', 4.5, 'uk', true),
('Economy Mastercard 1', 'Basic Mastercard', 89, 1200, 'mastercard', 'red', 4.5, 'us', true),
('Economy Mastercard 2', 'Basic Mastercard', 99, 1500, 'mastercard', 'red', 4.5, 'canada', true),
('Mid-Range Visa 1', 'Standard Visa card', 179, 2500, 'visa', 'blue', 4.6, 'us', true),
('Mid-Range Visa 2', 'Standard Visa card', 189, 2800, 'visa', 'blue', 4.6, 'germany', true),
('Mid-Range Mastercard 1', 'Standard Mastercard', 199, 3000, 'mastercard', 'red', 4.6, 'us', true),
('Mid-Range Mastercard 2', 'Standard Mastercard', 219, 3500, 'mastercard', 'red', 4.6, 'italy', true),
('Google Play Card 1', 'Google Play $50', 49, 50, 'gift card', 'multicolor', 4.7, 'us', true),
('Google Play Card 2', 'Google Play $100', 99, 100, 'gift card', 'multicolor', 4.7, 'us', true),
('Uber Gift Card 1', 'Uber $25', 25, 25, 'gift card', 'black', 4.6, 'us', true),
('Uber Gift Card 2', 'Uber $50', 50, 50, 'gift card', 'black', 4.6, 'us', true),
('DoorDash Gift Card', 'DoorDash $30', 30, 30, 'gift card', 'red', 4.5, 'us', true),
('Hulu Gift Card', 'Hulu 3 months', 39, 39, 'gift card', 'green', 4.6, 'us', true),
('Disney Plus Card', 'Disney+ 3 months', 29, 29, 'gift card', 'blue', 4.7, 'us', true),
('Max Gift Card', 'Max (HBO) 1 month', 20, 20, 'gift card', 'purple', 4.5, 'us', true),
('Paramount Card', 'Paramount+ 1 month', 12, 12, 'gift card', 'blue', 4.4, 'us', true),
('Walmart Gift Card 1', 'Walmart $50', 49, 50, 'gift card', 'blue', 4.7, 'us', true),
('Walmart Gift Card 2', 'Walmart $100', 99, 100, 'gift card', 'blue', 4.7, 'us', true),
('Target Gift Card 1', 'Target $50', 49, 50, 'gift card', 'red', 4.6, 'us', true),
('Costco Card', 'Costco $100', 99, 100, 'gift card', 'gold', 4.5, 'us', true);
