/*
  # Update card prices and balances

  This migration reduces all card prices to range from $25-$85 and
  reduces all balance amounts proportionally.
*/

DELETE FROM cards WHERE is_available = true;

INSERT INTO cards (title, description, price, balance, card_type, card_color, rating, country, is_available) VALUES
('Visa Basic 1', 'Basic Visa card', 29, 150, 'visa', 'blue', 4.5, 'us', true),
('Visa Basic 2', 'Basic Visa card', 31, 170, 'visa', 'blue', 4.5, 'uk', true),
('Visa Basic 3', 'Basic Visa card', 28, 140, 'visa', 'blue', 4.5, 'germany', true),
('Visa Basic 4', 'Basic Visa card', 32, 180, 'visa', 'blue', 4.5, 'canada', true),
('Visa Basic 5', 'Basic Visa card', 30, 160, 'visa', 'blue', 4.5, 'australia', true),
('Visa Standard 1', 'Standard Visa card', 42, 350, 'visa', 'blue', 4.6, 'us', true),
('Visa Standard 2', 'Standard Visa card', 45, 380, 'visa', 'blue', 4.6, 'uk', true),
('Visa Standard 3', 'Standard Visa card', 43, 365, 'visa', 'blue', 4.6, 'germany', true),
('Visa Standard 4', 'Standard Visa card', 46, 395, 'visa', 'blue', 4.6, 'italy', true),
('Visa Standard 5', 'Standard Visa card', 44, 375, 'visa', 'blue', 4.6, 'canada', true),
('Visa Premium 1', 'Premium Visa card', 65, 650, 'visa', 'blue', 4.8, 'us', true),
('Visa Premium 2', 'Premium Visa card', 68, 700, 'visa', 'blue', 4.8, 'uk', true),
('Visa Premium 3', 'Premium Visa card', 72, 750, 'visa', 'blue', 4.9, 'germany', true),
('Visa Premium 4', 'Premium Visa card', 70, 720, 'visa', 'blue', 4.8, 'canada', true),
('Visa Premium 5', 'Premium Visa card', 75, 800, 'visa', 'blue', 4.9, 'australia', true),
('Visa Premium 6', 'Premium Visa card', 73, 780, 'visa', 'blue', 4.8, 'italy', true),
('Visa Premium 7', 'Premium Visa card', 76, 820, 'visa', 'blue', 4.9, 'us', true),
('Visa Elite', 'Elite Visa card', 82, 950, 'visa', 'blue', 4.9, 'us', true),
('Mastercard Basic 1', 'Basic Mastercard', 30, 160, 'mastercard', 'red', 4.5, 'us', true),
('Mastercard Basic 2', 'Basic Mastercard', 32, 180, 'mastercard', 'red', 4.5, 'uk', true),
('Mastercard Basic 3', 'Basic Mastercard', 29, 150, 'mastercard', 'red', 4.5, 'germany', true),
('Mastercard Basic 4', 'Basic Mastercard', 33, 190, 'mastercard', 'red', 4.5, 'canada', true),
('Mastercard Basic 5', 'Basic Mastercard', 31, 170, 'mastercard', 'red', 4.5, 'italy', true),
('Mastercard Standard 1', 'Standard Mastercard', 44, 380, 'mastercard', 'red', 4.6, 'us', true),
('Mastercard Standard 2', 'Standard Mastercard', 47, 410, 'mastercard', 'red', 4.6, 'uk', true),
('Mastercard Standard 3', 'Standard Mastercard', 45, 390, 'mastercard', 'red', 4.6, 'germany', true),
('Mastercard Standard 4', 'Standard Mastercard', 48, 420, 'mastercard', 'red', 4.6, 'canada', true),
('Mastercard Standard 5', 'Standard Mastercard', 46, 400, 'mastercard', 'red', 4.6, 'italy', true),
('Mastercard Premium 1', 'Premium Mastercard', 68, 700, 'mastercard', 'red', 4.8, 'us', true),
('Mastercard Premium 2', 'Premium Mastercard', 71, 750, 'mastercard', 'red', 4.8, 'uk', true),
('Mastercard Premium 3', 'Premium Mastercard', 74, 800, 'mastercard', 'red', 4.9, 'germany', true),
('Mastercard Premium 4', 'Premium Mastercard', 72, 770, 'mastercard', 'red', 4.8, 'canada', true),
('Mastercard Premium 5', 'Premium Mastercard', 76, 840, 'mastercard', 'red', 4.9, 'australia', true),
('Mastercard Premium 6', 'Premium Mastercard', 75, 820, 'mastercard', 'red', 4.8, 'italy', true),
('Mastercard Premium 7', 'Premium Mastercard', 78, 880, 'mastercard', 'red', 4.9, 'us', true),
('Mastercard Elite', 'Elite Mastercard', 85, 980, 'mastercard', 'red', 4.9, 'us', true),
('AMEX Premium', 'American Express premium', 75, 850, 'amex', 'blue', 5.0, 'us', true),
('AMEX Premium UK', 'American Express premium', 78, 900, 'amex', 'blue', 4.9, 'uk', true),
('PayPal Transfer 1', 'PayPal balance transfer', 35, 400, 'paypal', 'blue', 4.9, 'us', true),
('PayPal Transfer 2', 'PayPal balance transfer', 48, 550, 'paypal', 'blue', 4.9, 'us', true),
('PayPal Transfer 3', 'PayPal balance transfer', 42, 480, 'paypal', 'blue', 4.8, 'uk', true),
('PayPal Transfer 4', 'PayPal balance transfer', 45, 520, 'paypal', 'blue', 4.8, 'canada', true),
('Amazon Gift Card 1', 'Amazon gift card $50', 50, 50, 'gift card', 'orange', 4.9, 'us', true),
('Amazon Gift Card 2', 'Amazon gift card $100', 85, 100, 'gift card', 'orange', 4.9, 'us', true),
('Amazon Gift Card 3', 'Amazon gift card $50 UK', 45, 50, 'gift card', 'orange', 4.8, 'uk', true),
('Apple Gift Card 1', 'Apple store gift card $25', 25, 25, 'gift card', 'gray', 4.8, 'us', true),
('Apple Gift Card 2', 'Apple store gift card $50', 48, 50, 'gift card', 'gray', 4.8, 'us', true),
('Apple Gift Card 3', 'Apple store gift card $50 UK', 45, 50, 'gift card', 'gray', 4.8, 'uk', true),
('Spotify Gift Card 1', 'Spotify premium 3 months', 35, 35, 'gift card', 'green', 4.7, 'us', true),
('Spotify Gift Card 2', 'Spotify premium 6 months', 65, 65, 'gift card', 'green', 4.7, 'us', true),
('Netflix Gift Card 1', 'Netflix 1 month', 18, 18, 'gift card', 'red', 4.6, 'us', true),
('Netflix Gift Card 2', 'Netflix 3 months', 48, 48, 'gift card', 'red', 4.6, 'us', true),
('Best Buy Gift Card 1', 'Best Buy $50', 48, 50, 'gift card', 'yellow', 4.8, 'us', true),
('Best Buy Gift Card 2', 'Best Buy $100', 82, 100, 'gift card', 'yellow', 4.8, 'us', true),
('PlayStation Card 1', 'PlayStation Store $25', 24, 25, 'gift card', 'blue', 4.7, 'us', true),
('PlayStation Card 2', 'PlayStation Store $50', 48, 50, 'gift card', 'blue', 4.7, 'us', true),
('Nintendo Card 1', 'Nintendo eShop $25', 24, 25, 'gift card', 'red', 4.6, 'us', true),
('Steam Gift Card 1', 'Steam $20', 19, 20, 'gift card', 'black', 4.8, 'us', true),
('Google Play Card 1', 'Google Play $25', 24, 25, 'gift card', 'multicolor', 4.7, 'us', true),
('Google Play Card 2', 'Google Play $50', 48, 50, 'gift card', 'multicolor', 4.7, 'us', true),
('Uber Gift Card 1', 'Uber $25', 25, 25, 'gift card', 'black', 4.6, 'us', true),
('DoorDash Gift Card', 'DoorDash $30', 29, 30, 'gift card', 'red', 4.5, 'us', true),
('Hulu Gift Card', 'Hulu 3 months', 35, 35, 'gift card', 'green', 4.6, 'us', true),
('Disney Plus Card', 'Disney+ 3 months', 27, 29, 'gift card', 'blue', 4.7, 'us', true),
('Walmart Gift Card 1', 'Walmart $25', 24, 25, 'gift card', 'blue', 4.7, 'us', true),
('Walmart Gift Card 2', 'Walmart $50', 48, 50, 'gift card', 'blue', 4.7, 'us', true),
('Target Gift Card 1', 'Target $25', 24, 25, 'gift card', 'red', 4.6, 'us', true);
